/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package mx.itson.benito.ui;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import mx.itson.benito.entidades.Articulo;
import mx.itson.benito.entidades.Compra;
import mx.itson.benito.entidades.Proveedor;
import mx.itson.benito.persistencia.ArticuloDAO;
import mx.itson.benito.persistencia.CompraDAO;
import mx.itson.benito.persistencia.ProveedorDAO;

/**
 *
 * @author PC
 */
public class CompraFormulario extends javax.swing.JDialog {
//

    int id = 0;

    /**
     * Creates new form CompraFormulario
     */
    public CompraFormulario(java.awt.Frame parent, boolean modal, int id) {
        super(parent, modal);
        initComponents();

        this.id = id;

        cargarConductores();
        cargarOficiales();

        cargarFormulario();

    }

    public void cargarConductores() {
        List<Articulo> articulos = ArticuloDAO.obtenerTodos();
        for (Articulo a : articulos) {
            cbxArticulos.addItem(a);
        }
    }

    public void cargarOficiales() {
        List<Proveedor> proveedores = ProveedorDAO.obtenerTodos();
        for (Proveedor p : proveedores) {
            cbxProveedores.addItem(p);
        }
    }

    public void cargarFormulario() {
        if (this.id != 0) {
            Compra c = CompraDAO.obtenerPorId(this.id);
            txtFolio.setText(c.getFolio());
            txtFecha.setText(c.getFecha().toString());
            cbxArticulos.setSelectedItem(c.getProveedor());
            cbxProveedores.setSelectedItem(c.getProveedor());
            cbxEstado.setSelectedItem(c.getEstado());
            txtIVA.setText(String.valueOf(c.getIva()));
            txtTotal.setText(String.valueOf(c.getTotal()));

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtFolio = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnComprar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cbxArticulos = new javax.swing.JComboBox<>();
        cbxProveedores = new javax.swing.JComboBox<>();
        txtTotal = new javax.swing.JLabel();
        txtIVA = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtSubtotal = new javax.swing.JLabel();
        cbxCantidad = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        cbxEstado = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Folio");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 26, -1, -1));
        getContentPane().add(txtFolio, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 42, 123, -1));

        jLabel2.setText("Fecha (yyyy-mm-dd)");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 70, -1, -1));

        txtFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaActionPerformed(evt);
            }
        });
        getContentPane().add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 92, 117, -1));

        jLabel3.setText("Articulos:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 159, -1, -1));

        btnComprar.setText("Compra");
        btnComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarActionPerformed(evt);
            }
        });
        getContentPane().add(btnComprar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 157, 58));

        jLabel6.setText("Cantidad");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 26, -1, -1));

        jLabel4.setText("IVA (%):");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 92, -1, -1));

        jLabel5.setText("Total (IVA incluido):");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, -1, -1));

        jLabel9.setText("Proveedores:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 159, -1, -1));

        getContentPane().add(cbxArticulos, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 187, 137, -1));

        getContentPane().add(cbxProveedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 187, 126, -1));
        getContentPane().add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(403, 159, -1, -1));

        txtIVA.setText("16");
        getContentPane().add(txtIVA, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 92, 20, -1));

        jLabel7.setText("Subtotal:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(403, 70, -1, -1));
        getContentPane().add(txtSubtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(403, 98, -1, -1));

        cbxCantidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61", "62", "63", "64", "65", "66", "67", "68", "69", "70", "71", "72", "73", "74", "75", "76", "77", "78", "79", "80", "81", "82", "83", "84", "85", "86", "87", "88", "89", "90", "91", "92", "93", "94", "95", "96", "97", "98", "99" }));
        cbxCantidad.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxCantidadItemStateChanged(evt);
            }
        });
        getContentPane().add(cbxCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 42, -1, -1));

        jLabel8.setText("Estado:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        cbxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ABIERTO", "CERRADO", "CANCELADO", " " }));
        getContentPane().add(cbxEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 120, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void btnComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarActionPerformed
        String folio = txtFolio.getText();
        String fechaString = txtFecha.getText().replace(" ", "-").replace("/", "-").replace(".", "-");
        String ivaString = txtIVA.getText();
        double iva = Double.parseDouble(ivaString);
        Articulo articuloSeleccionado = (Articulo) cbxArticulos.getSelectedItem();
        double precioArticulo = articuloSeleccionado.getPrecio();
        Proveedor proveedorSeleccionado = (Proveedor) cbxProveedores.getSelectedItem();
        int cantidad = Integer.parseInt(cbxCantidad.getSelectedItem().toString());
        double subtotal = cantidad * precioArticulo;
        double total = subtotal + (subtotal * (iva / 100));
        String estado = (String) cbxEstado.getSelectedItem();
        
        txtSubtotal.setText(String.valueOf(subtotal));
        txtTotal.setText(String.valueOf(total));

// Obtener instancias de Articulo y Proveedor seleccionados
        if (folio.isEmpty() || fechaString.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Favor de ingresar el folio y la fecha", "Campos vacíos", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                  SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");
                Date fecha = formato.parse(fechaString); // fecha en formato Date
                boolean resultado = this.id == 0
                        ? CompraDAO.guardar(folio, fecha, articuloSeleccionado, proveedorSeleccionado, cantidad, estado, iva, total)
                        : CompraDAO.editar(this.id, folio, fecha, articuloSeleccionado, proveedorSeleccionado, cantidad,estado, iva, total);

                if (resultado) {
                    JOptionPane.showMessageDialog(this, "Pedido realizado con éxito", "Pedido guardado", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "Ocurrio un error al guardar el Pedido", "Pedido no guardado", JOptionPane.ERROR_MESSAGE);
                }
            } catch (Exception ex) {
                // Manejo de excepciones
            }
        }


    }//GEN-LAST:event_btnComprarActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:

        CompraListado compraa = (CompraListado) SwingUtilities.getWindowAncestor(CompraFormulario.this);
        compraa.cargarTabla();


    }//GEN-LAST:event_formWindowClosed

    private void cbxCantidadItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxCantidadItemStateChanged
        String ivaString = txtIVA.getText();
        double iva = Double.parseDouble(ivaString);
        Articulo articuloSeleccionado = (Articulo) cbxArticulos.getSelectedItem();
        double precioArticulo = articuloSeleccionado.getPrecio();
        Proveedor proveedorSeleccionado = (Proveedor) cbxProveedores.getSelectedItem();
        int cantidad = Integer.parseInt(cbxCantidad.getSelectedItem().toString());
        double subtotal = cantidad * precioArticulo;
        double total = subtotal + (subtotal * (iva / 100));
        txtSubtotal.setText(String.valueOf(subtotal));
        txtTotal.setText(String.valueOf(total));
    }//GEN-LAST:event_cbxCantidadItemStateChanged

    private void txtFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CompraFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CompraFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CompraFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CompraFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CompraFormulario dialog = new CompraFormulario(new javax.swing.JFrame(), true, 0);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComprar;
    private javax.swing.JComboBox<Articulo> cbxArticulos;
    private javax.swing.JComboBox<String> cbxCantidad;
    private javax.swing.JComboBox<String> cbxEstado;
    private javax.swing.JComboBox<Proveedor> cbxProveedores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtFolio;
    private javax.swing.JLabel txtIVA;
    private javax.swing.JLabel txtSubtotal;
    private javax.swing.JLabel txtTotal;
    // End of variables declaration//GEN-END:variables
}
